# Define servers: "Title|IP|Port|User|Password|CommandForServerStop|MACAddress"

SERVERS=(
    '1|Android Server|192.168.1.101|8022|androidserver|$PASS1|bash|c8:9f:0c:ca:93:67'
    '2|LLM Server Small|192.168.1.104|22|llmserver|$PASS2|sudo -S systemctl suspend|b8:8a:60:96:35:cf'
    '3|LLM Server Medium|192.168.1.105|22|llmserver|$PASS3|sudo -S poweroff|c8:9f:0c:ca:93:67'
    '4|LLM Server Large|192.168.1.106|22|llmserver|$PASS4|sudo -S poweroff|c8:9f:0c:ca:93:67'
)
