# $HOME/homepage/config/services.yaml
# customActions call Flask API: http://localhost:9001/<action>/<server_id>
# which maps directly to: server_management_utilities.sh <server_id> <action>

- LLM Cluster:
    - LLM Server Small:
        icon: cpu
        href: http://192.168.1.52:5000
        ping: 192.168.1.14
        customActions:
          - name: Power On
            icon: play
            url: http://localhost:9001/switch_smart_plug_restart/2
          - name: Power Off
            icon: stop
            url: http://localhost:9001/stop_server/2

    - LLM Server Medium:
        icon: huggingface
        href: http://192.168.1.51:8000
        ping: 192.168.1.105
        customActions:
          - name: Power On
            icon: play
            url: http://localhost:9001/wake_server/3
          - name: Power Off
            icon: stop
            url: http://localhost:9001/stop_server/3

    - LLM Server Large:
        icon: ollama
        href: http://192.168.1.50:11434
        ping: 192.168.1.106
        customActions:
          - name: Power On
            icon: play
            url: http://localhost:9001/wake_server/4
          - name: Power Off
            icon: stop
            url: http://localhost:9001/stop_server/4
