# Define servers: "Title|IP|Port|User|Password|CommandForServerStop|MACAddress"

SERVERS=(
    '1|Android Server|192.168.1.101|8022|androidserver|$PASS1|bash|c8:9f:0c:ca:93:67'
    '2|LLM Server Mini|192.168.1.104|22|llmserver|$PASS2|sudo -S systemctl suspend|34:60:f9:f5:38:f5'
    '3|LLM Server Small|192.168.1.105|22|llmserver|$PASS3|sudo -S poweroff|70:4d:7b:34:9f:4c'
    '4|LLM Server Medium|192.168.1.106|22|llmserver|$PASS4|sudo -S systemctl suspend|50:eb:f6:ba:bd:42'
    '5|LLM Server Large|192.168.1.107|22|llmserver|$PASS5|sudo -S systemctl suspend|34:5a:60:db:ae:32'
)
