# $home/homepage/config/services.yaml
- LLM Cluster:
    - Matter Smart Plug:
        icon: ollama
        href: http://192.168.1.200
        ping: 192.168.1.200
    - LLMServerSmall:
        icon: ollama
        href: http://192.168.1.104:8081
        ping: 192.168.1.104
    - LLMServerMedium:
        icon: ollama
        href: http://192.168.1.105:8081
        ping: 192.168.1.105
    - LLMServerLarge:
        icon: ollama
        href: http://192.168.1.106:8081
        ping: 192.168.1.106


- Repositories:
    - PrivateContext:
        icon: github
        href: https://github.com/iamtanmay/PrivateContext
    - ServerManagement:
        icon: github
        href: https://github.com/iamtanmay/ServerManagement

- Monitoring:
    - Monitoring:
        icon: reddit
        href: https://github.com/iamtanmay/ServerManagement

- Homepage:
    - DisconnectedAI:
        icon: youtube
        href: https://www.disconnected-ai.com/

