# $home/homepage/config/services.yaml
- LLM Cluster:
    - Matter Smart Plug:
        icon: ollama
        href: http://192.168.1.200
        ping: 192.168.1.200
    - LLMServerSmall:
        icon: ollama
        href: http://192.168.1.104:8081
        ping: 192.168.1.104
    - LLMServerMedium:
        icon: ollama
        href: http://192.168.1.105:8081
        ping: 192.168.1.105
    - LLMServerLarge:
        icon: ollama
        href: http://192.168.1.106:8081
        ping: 192.168.1.106
- File Servers:
    - MediaServer:
        icon: openmediavault
        href: http://192.168.1.101:9001/MediaServer
        widget:
          type: iframe
          url: http://192.168.1.101:9001/MediaServer
          height: 500 # Adjust this height to fit your screen

